export const PAGES = [
  { title: 'Colors' },
  { title: 'Typograpy'},
  { title: 'Ionography'},
  { title: 'Textfields'},
  { title: 'Comboboxs'},
  { title: 'Multi-Selector Comboboxs'},
  { title: 'Multi-Seletors'},
  { title: 'RadioButtons'},
  { title: 'Checkboxs'},
  { title: 'Pickers: Date / Time'},
  { title: 'Inputs: Currency / Percentage'},
  { title: 'Inputs: Variation'},
  { title: 'Inputs: Other'},
  { title: 'Weekdays Selector'},
  { title: 'Buttons: Primary / Secondary / Terciary'},
  { title: 'Buttons: Other actions'},
  { title: 'Search & Filters'},
  { title: 'Tabs'},
  { title: 'Tables'},
  { title: 'Modals'},
  { title: 'Tooltips'},
  { title: 'Infos & Tags'},
  { title: 'Base Structure'},
  { title: 'Page Headers'},
  { title: 'Forms'},
  { title: 'Sidebar'},
  { title: 'Translate'},
];
